# Generated by Django 5.1.4 on 2025-01-09 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fact_app', '0003_alter_invoice_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_type',
            field=models.CharField(choices=[('R', 'RECU'), ('F', 'FACTURE')], max_length=1),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
